apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-db-pvc
  namespace: default
  labels:
    app: quiz
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
